name: mvvm_template
description: Flutter MVVM Template, using provider

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  provider: ^6.0.5
  modal_progress_hud_nsn: ^0.4.0
  intl: ^0.18.1
  sqflite: ^2.3.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
